on: push
jobs:
  install:
    strategy:
      matrix:
        system:
        - ubuntu-latest
        - macos-latest
    runs-on: matrix.system
    steps:
    - run: curl https://cml.sh | sh
    - run: cml --version
    - run: curl https://cml.sh | sh -s v0.12.0
    - run: cml --version | grep 0.12.0
 
Wed Oct 23 18:44:20 UTC 2024
