on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: iterative/setup-cml@v1
    - run: date > file && cml pr .
      env:
        GITHUB_TOKEN: ${{ github.token }}
