on: pull_request
concurrency: ${{ github.workflow }}
jobs:
  test:
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.head_ref || github.ref }}-${{ matrix.provider }}
      cancel-in-progress: true
    steps:
    - run: for ((count=0; count<10; count++)); do sleep 10; done
