on: push
jobs:
  fails:
    runs-on: ubuntu-latest
    steps:
    - run: wget https://github.com/iterative/dvc/releases/download/2.10.1/dvc_2.10.1_amd64.deb && sudo apt install ./dvc_2.10.1_amd64.deb
    - run: dvc doctor && dvc metrics show
  succeeds:
    runs-on: ubuntu-latest
    steps:
    - run: pip3 install dvc==2.10.0
    - run: dvc doctor && dvc metrics show
