on: push
jobs:
  fails:
    runs-on: ubuntu-latest
    steps:
    - uses: iterative/setup-dvc@v1
    - run: dvc doctor && dvc metrics show
  succeeds:
    runs-on: ubuntu-latest
    steps:
    - run: pip install dvc
    - run: dvc doctor && dvc metrics show
