on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
