on: workflow_dispatch
permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - env:
          REPO_TOKEN: ${{ github.token }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: >-
          cml-runner
          --cloud=aws
          --cloud-region=us-west-1
          --cloud-type=t2.micro
          --idle-timeout=60
          --labels=debug
  test:
    needs: deploy
    runs-on: [self-hosted, debug]
    steps:
      - run: |
          cat /etc/docker/daemon.json || true
          docker run --rm -it dvcorg/cml:0-dvc2-base1 date || true
