on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - run: >-
          cml-runner \
          --cloud aws \
          --cloud-region us-east-2 \
          --cloud-type=g3.4xlarge \
          --cloud-hdd-size 64 \
          --labels=cml-runner \
          --cloud-ssh-private="$AWS_SSH"
        env:
          AWS_SSH: ${{ secrets.AWS_SSH }}
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  run:
    needs: deploy
    runs-on: self-hosted
    steps:
      - uses: mxschmitt/action-tmate@v3
