on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - env:
          repo_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          ssh-keygen -t rsa -m pem -N "" -b 2048 -f "$(mktemp -u)"
          cat $_
          cml-runner \
          --cloud aws \
          --cloud-region us-east-2 \
          --cloud-type=g3.4xlarge \
          --cloud-hdd-size 64 \
          --labels=cml-runner \
          --cloud-ssh-private="$(perl -pe 's/\n/\\n/g' "$_")"
  run:
    needs: deploy
    runs-on: self-hosted
    steps:
      - uses: mxschmitt/action-tmate@v3
