on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: >-
          cml-runner
          --cloud aws
          --cloud-region us-west-1
          --cloud-type=t2.micro
          --idle-timeout 60
  train:
    needs: deploy
    runs-on: self-hosted
    container: docker://dvcorg/cml:0-dvc2-base1
    steps:
      - uses: mxschmitt/action-tmate@v3
