on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: hashicorp/terraform
    steps:
      - run: apk add curl git && curl https://cml.sh | sh
      - run: git config --get remote.origin.url
      - run: cml runner --cloud=aws
      
