on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: hashicorp/terraform
    steps:
      - run: apk add curl git && curl https://cml.sh | sh
      - run: cml --version
      - run: cml runner --cloud=aws
      
