on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      #- uses: mxschmitt/action-tmate@v3
      #  with:
      #    limit-access-to-actor: true
      - run: |
          date | tee a && cml pr a
          git branch
          cml send-comment --pr --update <(date)
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }} # ${{ github.token }}
