on: push
jobs:
  install:
    strategy:
      fail-fast: false
      matrix:
        system:
        - ubuntu-latest
        - macos-latest
        container:
        - ubuntu
        - alpine
        - ""
    runs-on: ${{ matrix.system }}
    container: ${{ matrix.container }}
    steps:
    - if: matrix.container == 'alpine'
      run: apt update && apt install --yes curl
    - if: matrix.container == 'alpine'
      run: apk add curl
    - run: curl https://cml.sh | sh
    - run: cml --version
    - run: curl https://cml.sh | sh -s v0.12.0
    - run: cml --version | grep 0.12.0
