on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: hashicorp/terraform
    steps:
      - run: chown -R 0:0 $(realpath .)
      - run: apk add curl && curl https://cml.sh | sh
      - run: cml runner --cloud=aws
      
