on: push
jobs:
  fix:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml
    steps:
      - uses: actions/checkout@v3
      - run: git config --global --add safe.directory .
      - run: cml ci
        env:
          GITHUB_TOKEN: ${{ github.token }}
