on: push
jobs:
  fix:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml
    steps:
      - uses: actions/checkout@v3
      - uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
