on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: iterative/setup-cml@v1
      - run: echo "# Lorem Ipsum" > report.md && cml send-github-check report.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
