on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - run: |
          f=$(uuidgen)
          date | tee $f
          cml pr $f
          cml send-comment --pr --update <(date)
        env:
          GITHUB_TOKEN: ${{ github.token }}
