on: push
jobs:
  bad:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml
    steps:
      - uses: actions/checkout@v3
      - run: git --version
      - run: cml ci
        env:
          GITHUB_TOKEN: ${{ github.token }}
  good:
    runs-on: ubuntu-latest
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v3
      - run: git --version
      - run: cml ci
        env:
          GITHUB_TOKEN: ${{ github.token }}
