on: push
jobs:
  example:
    steps:
      - run: >-
          node -e
          'require("child_process").execFile("node", ["-e", process.argv[1]], console.log)'
          'require("fs").readSync(0, Buffer.alloc(1))'
    runs-on: ${{ matrix.system }}
    strategy:
      matrix:
        system:
          - ubuntu-latest # works
          - macos-latest # hangs
          - windows-latest # hangs
