on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$JSON"
        env:
          JSON: ${{ toJson(          {event_type:new-cml, client_payload:{tag:github.sha}}          ) }}
