on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: hashicorp/terraform
    steps:
      - uses: actions/checkout@v3
      - run: apk add curl && curl https://cml.sh | sh
      - run: cml runner --cloud=aws
      
