on: push
jobs:
  example:
    steps:
      - name: 1
        shell: bash
        run: node -e 'process.stdin; require("fs").readSync(0, Buffer.alloc(1))' <(cat)
      - name: 2
        shell: bash
        run: node -e 'require("fs").readSync(0, Buffer.alloc(1))' <(cat)
    runs-on: ${{ matrix.system }}
    strategy:
      matrix:
        system:
          - ubuntu-latest # 2 hangs
          - macos-latest # 2 hangs
          - windows-latest # both hang
