on:
  pull_request:
    types: [closed]
jobs:
  notify:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - if: contains(github.event.pull_request.labels.*.name, 'security')
        run: printenv SLACK_MESSAGE | jq --raw-input {text:.} | curl --header "Content-Type: application/json" --data-binary=@- "$SLACK_WEBHOOK"
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: ${{ github.actor }} merged ${{ github.event.pull_request.title }}
