on:
  pull_request:
    types: [closed]
jobs:
  notify:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - if: |
        contains(github.event.pull_request.labels.*.name, 'security') ||
        contains(github.event.pull_request.labels.*.name, 'bug')
      run: |
        printenv SLACK_MESSAGE |
        jq --raw-input --slurp {text:.} |
        curl --data-binary @- "$SLACK_WEBHOOK"
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: |
          ${{ github.actor }}
          ${{ github.event.pull_request.title }}
          ${{ github.event.pull_request.html_url }}
