on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v3
    - run: pip install git+https://github.com/iterative/dvc#egg=dvc[s3]
    - run: dvc doctor
    - run: dvc plots diff
