on: workflow_dispatch
jobs:
  deploy-runner:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: iterative/setup-cml@v1
    - run: echo
      env:
        REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}             
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  train-model:
    needs: deploy-runner
    runs-on: [self-hosted, gpu]
    steps:
    - uses: actions/checkout@v2
    - run: |
        pip install -r requirements.txt
        python train.py
