on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - run: |
          date > file
          gh pr merge --rebase $(cml pr file)
        env:
          GITHUB_TOKEN: ${{ github.token }}
