on: push
jobs:
  create:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: [1, 2, 3]
    steps:
    - run: date > file-${{ matrix.file }}
    - uses: actions/upload-artifact@v2
      with:
        name: files
        path: file-*
  read:
    needs: create
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: files
    - run: find
