on: push
jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: >
        npx github:iterative/cml runner launch
        --labels=${{ github.run_id }}-${{ github.run_attempt }}
        --idle-timeout=60
      env:
        REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  job:
    strategy:
      matrix:
        test: [1, 2]
      max-parallel: 1
    runs-on:
      - self-hosted
      - ${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: sleep 120 # more than --idle-timeout=60 above
