on: workflow_dispatch
jobs:
  launch:
    runs-on: ubuntu-latest
    steps:
    - uses: iterative/setup-cml@v1
    - run: env && cml runner launch --idle-timeout=60 --labels=unique
      env:
        CML_DRIVER_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  reproduce:
    needs: launch
    runs-on: [self-hosted, unique]
    steps:
      - run: sleep 120 # more than --idle-timeout=60 above
