on: push
jobs:
  ldid:
    runs-on: ubuntu-latest
    steps:
    - run: conda install ldid
  yes:
    uses: ./.github/workflows/test.yml
    with:
      release: true
  no:
    uses: ./.github/workflows/test.yml
    with:
      release: false
