on: push
jobs:
  ldid:
    runs-on: ubuntu-latest
    steps:
    - run: conda config --add channels conda-forge && conda install ldid
    - run: $CONDA/bin/ldid
  yes:
    uses: ./.github/workflows/test.yml
    with:
      release: true
  no:
    uses: ./.github/workflows/test.yml
    with:
      release: false
