on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - uses: iterative/setup-cml@sudo-e
      with:
        sudo: true
    - run: cml-publish /dev/null
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
