on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - uses: iterative/setup-cml@v1
    - run: |
        convert -size 100x100 xc:red test.png
        cml-publish test.png
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
