on: pull_request
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - name: Create report
        run: |
          echo "## Hello!" >> report.md
          cml-send-comment report.md
        env:
          REPO_TOKEN: ${{ github.token }}
