on:
  schedule:
  - cron: '* * * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: |
        cat > main.tf <<END
        terraform {
          required_providers {
            iterative = {
              source = "iterative/iterative"
            }
          }
        }
        END
        terraform init
